# ruff: noqa: E501
"""Dependency-free authenticated operator console for the self-hosted MVP."""

DASHBOARD_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>For8killo | Foreight Console</title><style>
:root{color-scheme:dark;--bg:#050b16;--panel:#0d192b;--line:#233653;--cyan:#67e8f9;--green:#86efac;--red:#fda4af;--muted:#9fb0c9}*{box-sizing:border-box}
body{font:15px/1.5 Inter,ui-sans-serif,system-ui;background:radial-gradient(circle at 80% 0,#102c47,var(--bg) 42%);color:#e5efff;margin:0;min-height:100vh}main{max-width:1200px;margin:auto;padding:28px}header{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:22px}h1{font-size:32px;margin:0;color:var(--cyan)}h1 span{color:#fff;font-weight:400}h2{font-size:16px;margin:0 0 12px}.pill{padding:7px 11px;border:1px solid #286044;border-radius:999px;color:var(--green);background:#092116}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}.card{grid-column:span 4;background:linear-gradient(145deg,#101f34,#0a1424);border:1px solid var(--line);border-radius:15px;padding:17px;min-height:140px}.wide{grid-column:span 8}.full{grid-column:1/-1}label{display:block;color:var(--muted);font-size:12px;margin-bottom:5px}input,select,button{font:inherit;border-radius:8px;border:1px solid #314968;padding:10px;background:#081221;color:#eef6ff}input{width:100%}button{cursor:pointer;background:#12304b;border-color:#276083}button:hover{background:#174365}.row{display:flex;gap:9px;align-items:end}.grow{flex:1}pre{white-space:pre-wrap;word-break:break-word;max-height:380px;overflow:auto;color:#c8dcf5;margin:0}.muted{color:var(--muted)}.danger{color:var(--red)}#error{min-height:24px;margin:8px 0;color:var(--red)}@media(max-width:760px){.card,.wide{grid-column:1/-1}header{align-items:flex-start;flex-direction:column}.row{flex-wrap:wrap}}
</style></head><body><main><header><div><h1>For8killo <span>/ Foreight</span></h1><div class="muted">Evidence-led market intelligence and paper operations</div></div><div id="mode" class="pill">PAPER · CHECKING</div></header>
<section class="grid"><div class="card full"><h2>Connect securely</h2><div class="row"><div class="grow"><label for="key">Installation API key (held only in this page)</label><input id="key" type="password" autocomplete="off" placeholder="key-id.secret"></div><button id="connect">Connect</button></div><div id="error"></div></div>
<div class="card"><h2>Runtime</h2><pre id="health">Not connected</pre></div><div class="card"><h2>Safety control</h2><pre id="ops">Not connected</pre></div><div class="card"><h2>Paper portfolio</h2><pre id="portfolio">Not connected</pre></div>
<div class="card wide"><h2>Market evidence</h2><div class="row"><div class="grow"><label for="instrument">Instrument</label><select id="instrument"><option>EUR_USD</option><option>XAU_USD</option><option>BTC_USD</option></select></div><button id="analyze">Analyze</button><button id="signal">Generate paper signal</button></div><pre id="analysis" class="muted">Connect, then select an instrument.</pre></div>
<div class="card"><h2>Ranked opportunities</h2><button id="refresh-signals">Refresh</button><pre id="signals" class="muted">No data loaded.</pre></div>
<div class="card full"><h2>Ask Foreight</h2><div class="row"><input id="question" class="grow" maxlength="2000" placeholder="Explain health, signals, positions, performance, or strategy"><button id="ask">Ask</button></div><pre id="answer" class="muted">Answers use verified local state and approved research.</pre></div></section>
<p class="danger">Research and paper practice only. No profitability is guaranteed. Live-money execution is unavailable.</p></main><script>
const $=id=>document.getElementById(id),show=(id,data)=>$(id).textContent=JSON.stringify(data,null,2);let key="",conversation=crypto.randomUUID();async function api(path,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${key}`};if(options.body)headers["Content-Type"]="application/json";const response=await fetch(path,{...options,headers});const data=await response.json();if(!response.ok)throw new Error(data.detail||`Request failed (${response.status})`);return data}async function run(work){$("error").textContent="";try{await work()}catch(error){$("error").textContent=error instanceof Error?error.message:String(error)}}async function refresh(){const [health,ops,portfolio,instruments,signals]=await Promise.all([fetch("/health").then(r=>r.json()),api("/api/v1/operations/status"),api("/api/v1/portfolio"),api("/api/v1/instruments"),api("/api/v1/signals")]);show("health",health);show("ops",ops);show("portfolio",portfolio);show("signals",signals);$("instrument").replaceChildren(...instruments.map(i=>Object.assign(document.createElement("option"),{value:i.symbol,textContent:`${i.symbol} · ${i.asset_class}`})));$("mode").textContent=`PAPER · KILL SWITCH ${ops.kill_switch_active?"ACTIVE":"CLEAR"}`}
$("connect").onclick=()=>run(async()=>{key=$("key").value.trim();await refresh()});$("analyze").onclick=()=>run(async()=>show("analysis",await api(`/api/v1/analysis/${encodeURIComponent($("instrument").value)}`)));$("signal").onclick=()=>run(async()=>{show("analysis",await api(`/api/v1/signals/${encodeURIComponent($("instrument").value)}`,{method:"POST"}));show("signals",await api("/api/v1/signals"))});$("refresh-signals").onclick=()=>run(async()=>show("signals",await api("/api/v1/signals")));$("ask").onclick=()=>run(async()=>show("answer",await api("/api/v1/conversations/ask",{method:"POST",body:JSON.stringify({conversation_id:conversation,question:$("question").value})})));fetch("/health").then(r=>r.json()).then(data=>show("health",data));
</script></body></html>"""
